DROP TABLE IF EXISTS pokemon;

CREATE TABLE pokemon (
  ID INT PRIMARY KEY,
  POKEMON_NAME VARCHAR(250) NOT NULL
);

INSERT INTO pokemon (ID, POKEMON_NAME) VALUES
  (1, 'Bulbasaur'),
  (2, 'Charmander')